---
- hosts: ubuntu
  become: yes
  tasks:
  - name: to install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: to install tree
    apt:
      name: tree
      state: present
 
 